optimizer: cosangulargrad
scheduler:
  type: CosineAnnealingWarmRestarts
  T_mult: 1
  T_0: 10
  eta_min: 1e-6
model:
  backbone: tf_efficientnet_b4_ns
precision: 32
grad_clip: 0.5
train_params:
  img_size: 512
  grad_starvation_fix: True
  epochs: 200
  lr: 5e-4
  num_workers: 4
  csv: /home/jovyan/kaggle/covid/train_folds.csv