optimizer: adamw_gcc2
num_workers: 4
backbone: deit_small_patch16_224
head: v1
img_size: 224
aug: '2'
crit: smooth
scheduler:
  type: CosineAnnealingWarmRestarts
  T_mult: 2
  T_0: 10
  eta_min: 1e-8
train_params:
  epochs: 80
  lr: 5e-4
  num_workers: 4
  batch_size: 16
  precision: 16
  clip_grad: 2.0