optimizer: adamw_gcc2
backbone: resnet18
head: v1
n_out: 512
img_size: 512
trn_path: input/train_merged
csv_path: input/train_folds_merged.csv
crit: smooth
aug: '2'
grad_clip: 2.0
precision: 32
scheduler:
  type: CosineAnnealingWarmRestarts
  T_mult: 2
  T_0: 10
  eta_min: 1e-8
train_params:
  epochs: 200
  lr: 5e-4
  num_workers: 4
  batch_size: 16
  fold: 0